name: CI

on:
  push:
    branches: [ master ]
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: clippy, llvm-tools-preview
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build and Test
      run: |
        cargo build --verbose
        cargo test --verbose
    - name: Run Clippy
      run: cargo clippy --all-features --all -- -D warnings
    - name: Security audit
      run: cargo audit
    - name: Generate Coverage
      run: |
        mkdir -p coverage
        cargo install cargo-llvm-cov
        cargo llvm-cov --tests --lcov --output-path=coverage/coverage.lcov
    - name: Upload Coverage
      uses: codecov/codecov-action@v2
      with:
        directory: coverage

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - uses: actions/checkout@v3
    - name: Get Release Version
      run: echo "name=VERSION::${GITHUB_REF/refs\/tags\//}" > $GITHUB_OUTPUT
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: gsn2x
    - name: Deploy Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
        prerelease: false
        title: ${{ steps.get_version.outputs.VERSION }}
        files: |
          gsn2x-*
